# Generated by Django 3.2.20 on 2023-08-08 14:06

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0015_inputtextelement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultThemeComponent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_color", models.CharField(default="#000000ff", max_length=9)),
                (
                    "secondary_color",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                ("heading_1_font_size", models.SmallIntegerField(default=24)),
                (
                    "heading_1_color",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                ("heading_2_font_size", models.SmallIntegerField(default=20)),
                (
                    "heading_2_color",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                ("heading_3_font_size", models.SmallIntegerField(default=16)),
                (
                    "heading_3_color",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                (
                    "button_background_color",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                (
                    "button_font_color",
                    models.CharField(default="#ffffffff", max_length=9),
                ),
                (
                    "button_font_size",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                ("button_border_radius", models.SmallIntegerField(default=0)),
                ("button_border_size", models.SmallIntegerField(default=0)),
                (
                    "button_border_color",
                    models.CharField(default="#000000ff", max_length=9),
                ),
                ("button_horizontal_padding", models.SmallIntegerField(default=12)),
                ("button_vertical_padding", models.SmallIntegerField(default=6)),
                (
                    "builder",
                    baserow.core.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defaultthemecomponent",
                        to="builder.builder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
