import { TestApp } from '@baserow/test/helpers/testApp'
import { RuntimeFunctionCollection } from '@baserow/modules/core/functionCollection'
import { ToTipTapVisitor } from '@baserow/modules/core/formula/toTipTapVisitor'
import parseBaserowFormula from '@baserow/formula/parser/parser'
import testCases from '@baserow_test_cases/tip_tap_visitor_cases.json'

describe('toTipTapVisitor', () => {
  const TYPES_WITH_NO_ID = ['text', 'hardBreak']

  let testApp = null
  beforeAll(() => {
    testApp = new TestApp()

    // Make sure the ID is not checked since is auto generated by the visitor
    testCases.forEach((testCase) => {
      testCase.content.forEach((content) => {
        if (
          !TYPES_WITH_NO_ID.includes(content.type) &&
          content.attrs?.id === undefined
        ) {
          content.attrs = { ...content.attrs, id: expect.any(String) }
        }
      })
    })
  })

  testCases.forEach(({ formula, content }) => {
    it('should return the expected formula', () => {
      const functionCollection = new RuntimeFunctionCollection(
        testApp.store.$registry
      )
      const tree = parseBaserowFormula(formula)
      const result = new ToTipTapVisitor(functionCollection).visit(tree)
      expect(result).toEqual(content)
    })
  })
})
