# Generated by Django 3.2.20 on 2023-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_notifications_queued"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrecipient",
            name="sent_by_email",
            field=models.BooleanField(
                default=True,
                help_text="If True, then the notification has been sent by email to the user. This field is only used for direct notifications.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notification_frequency",
            field=models.TextField(
                choices=[
                    ("instant", "instant"),
                    ("daily", "daily"),
                    ("weekly", "weekly"),
                    ("never", "never"),
                ],
                default="instant",
                max_length=16,
            ),
        ),
    ]
