# Generated by Django 3.2.20 on 2023-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_notifications_sent_by_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrecipient",
            name="sent_by_email",
            field=models.BooleanField(
                default=False,
                help_text="If True, then the notification has been sent by email to the user. This field is only used for direct notifications.",
            ),
        ),
    ]
